### PR TITLE
Basic milk network created in Composer Playground

### PR DESCRIPTION
**Pull request by acourtney2015**
To test the basic first network draft: Download the breast-milk-network.bna file onto your computer--->Open https://composer-playground.mybluemix.net/editor inside your browser. Click "Let's BlockChain" ---->Click "Deploy a new business network"----> Click "Browse" under Drop here to upload or browse-----> navigate to the .bna file on your computer and double click. The network should open on the right--->Click Blue "Deploy" button--->on the left click "Connect now" under the network on the left. Have fun testing it!

### CODE REVIEW

**Comment by tkuhrt** [comment]
Hi, @acourtney2015. I would recommend checking in the actual source files that went into creating this BNA file. The BNA file is an archive file that does not allow anyone to edit the contents.

Also, when you do a commit, make sure you use the -s option to sign off the commit.

**Comment by acourtney2015** [comment]
Hi, tkuhrt!-->. bna file uploaded for ease of entire group to open the network in playground and test functionality. I have another draft of the network with more advanced features that I intend to upload. Need help in getting transit code to work. Can upload the individual files for the more advanced one. Not sure where -s option resides. (not committing using command line). Please give guidance. Thanks!

**Comment by MariLeigh** [comment]
@acourtney2015 the sign-off is tricky! You need to use the following format 

Signed-off-by: Haitao Yue <hightall@me.com>

What was trick for me was finding the right email, because I've set Github not to share my email address. To find the email go here: https://github.com/settings/emails

Under Primary Emails you'll see what you need, mine looks like this - 
 Primary email address

"Because you have email privacy enabled, mari.iannarone@gmail.com will be used for account-related notifications and 35410257+MariLeigh@users.noreply.github.com will be used for web-based GitHub operations (e.g. edits and merges)."

so my sign off is 
Signed-off-by: Marissa Iannarone <35410257+MariLeigh@users.noreply.github.com>

**Comment by ryjones** [comment]
@MariLeigh that isn't a valid email address, though. If we need to resolve who you are, legally, the no reply address goes nowhere.

**Comment by MariLeigh** [comment]
@ryjones very good point. I will change my email settings then.

**Comment by acourtney2015** [comment]
I am closing the pull request to add the files to the main branch. Would like the current files uploaded to remain inside the acourtney2015-patch-1 branch as the files continue to be worked upon. Hope this is correct way to do that. Thanks!

**Pull request closed without merging**
